Eshop/Eshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls'))
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Eshop/store/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, register, user_login, user_logout, add_to_cart, cartItem,payment_product,payment_success

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home.as_view(), name='home'),
    path('login/', user_login, name='login'),
    path('register/', register, name='register'),
    path('logout/', user_logout, name='logout'),
    path('cart/', add_to_cart, name='cart'),
    path('payment/',payment_product,name='payment'),
    path('payment_success',payment_success,name='payment_success'),
    
    
  
]

Eshop/store/models.py
# products/models.py

from django.db import models
from django.contrib.auth.models import User
class Item(models.Model):
    name = models.CharField(max_length=100)
    image=models.ImageField(upload_to='item_images/',blank=True,null=True)
    price = models.DecimalField(max_digits=6, decimal_places=0)

    def __str__(self):
        return self.name

class cartItem(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    item=models.ForeignKey('Item',on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)
    @property
    def total_price(self):
        return self.item.price* self.quantity
# Create your models here.
class PaymentDetail(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    product_name=models.CharField(max_length=100)
    price=models.DecimalField(max_digits=10,decimal_places=0)
    
    payment_id=models.CharField(max_length=100)
    def __str__(self):
        return f"{self.name}-{self.product_name}-{self.price}" 

Eshop/store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.contrib.auth import authenticate,login,logout
from .models import Item,cartItem
from django.views import View
import time
from django.conf import settings

class home(View):
    def post(self,request):
        product=request.POST.get('item')
        print(product)
    def get(self,request):
         items=Item.objects.all()
         return render(request,'home.html',{'items':items})
 

def register(request):
    if request.method == 'POST':
        name = request.POST.get('uname')
        uname = request.POST.get('username')
        pass1 = request.POST.get('password')
        pass2 = request.POST.get("conpass")
        if pass1 != pass2 :
            return render(request, 'register.html',{'erro_message':'password does not match.please enter password again.'})
        else:
            if User.objects.filter(username=name).exists():
                return render(request, 'register.html', {'error_message': 'Username already exists. Please choose a different username.'})
            else:
                
                my_user = User.objects.create_user(name, uname, pass1)
                my_user.save()
                return redirect("home")

    return render(request, 'register.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            return render(request, "login.html")

    return render(request, 'login.html')
def user_logout(request):
    logout(request)
    return redirect(user_login)
    
def add_to_cart(request):
    if request.method=='POST':
        item_id=request.POST.get('item')
        item=Item.objects.get(pk=item_id)
        cart_item,created=cartItem.objects.get_or_create(item=item,user=request.user)
        cart_item.quantity+=1
        cart_item.save()
        return render(request,'cart.html')
    return render(request,'cart.html') 

import razorpay
from django.conf import settings
from django.shortcuts import render
from .models import PaymentDetail
def payment_product(request):
    if request.method == 'POST':
        amount = request.POST.get('amount')
        order_id = request.POST.get('order_id')
        amount_in_paisa = int(float(amount) * 100)
        client = razorpay.Client(auth=(settings.RAZORPAY_API_KEY, settings.RAZORPAY_SECRET_KEY))
        razorpay_order = client.order.create(dict(amount=amount_in_paisa, currency='INR'))
        razorpay_order_id = razorpay_order['id']
        return render(request, 'payment.html', {'amount': amount_in_paisa, 'order_id': int(order_id), 'razorpay_order_id': razorpay_order_id})
    else:
        return render(request, 'payment.html')
def payment_success(request):
    if request.method=='POST':
         
        #  payment_id=request.POST.get('razorpay_payment_id')
        #  order_id=request.POST.get('razorpay_order_id')
        #  signature=request.POST.get('razorpay_signature')
        #  item=Item.objects.get(pk=order_id)
        #  payment_detail = PaymentDetail.objects.create(
        #     name=request.user.username,  
        #     email=request.user.email,
        #     product_name=item.name,
        #     price=item.price,
        #     payment_id=payment_id,
        # )
         
         return render(request,'payment_success.html')
    else:
        return render(request, 'payment.html')
    

Eshop/store/templates/cart.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <h1>your cart</h1>
    <form action="" method="POST">
        {%csrf_token%}
        <ul>
            {% for cart_item in user.cartitem_set.all%}
            <li>
                {{cart_item.item.name}}-quantity:{{cart_item.quantity}}
                <button type="submit" name="plus" value="{{cart_item.id}}">+</button>  
                <button type="submit" name="minus" value="{{cart_item.id}}">-</button>       
            </li>
            {%endfor%}
        </ul>
    </form>
    
</body>
</html>        

Eshop/store/templates/home.html
{% load static%}
{% block page_content%}
<!DOCTYPE html>
<html>
<head>
  <title>auntystore</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{% static 'css/home.css' %}" rel="stylesheet">
</head>
<body>
  <header>
    <h1>AUNTY STORE:EXPECT MORE ,PAY LESS</h1>
    <nav>
      <a href="#" id='home'>Home</a>
     
    {% if user.is_authenticated %}
    <a href={% url 'cart'  %} id="cart">Cart</a>
    <p>Welcome, {{ user.username }}!</p>
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    {% endif %}
    </nav>
    
  </header>

  <div class="container">
    <div class="categories">
      <h2>Categories</h2>
      <ul>
        <li><a href="#">Category 1</a></li>
        <li><a href="#">Category 2</a></li>
        <li><a href="#">Category 3</a></li>
        <li><a href="#">Category 4</a></li>
        <!-- Add more categories if needed -->
      </ul>
    </div>

    <div class="items">
      {% for item in items %}
      <div class="item">
        <img src="{{item.image.url}}" alt="{{item.name}} Image">
        <h3>{{item.name}}</h3>
        <p>Description of the product 1.</p>
        <span class="price">Rs{{item.price}}</span>
        {% if user.is_authenticated %}
                <form action="{% url 'payment' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="amount" value="{{ item.price }}">
                    <input type="hidden" name="order_id" value="{{ item.id }}">
                    <input type="submit" value="Buy Now" class="button">  
                </form>
                <form action="{% url 'cart' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" name="item" value="{{ item.id }}">
                  <input type="submit" value="Add to Cart" class="button">
              </form>
            {% else %}
                <a href="{% url 'login' %}" class="button">Login to Buy</a>
            {% endif %}
        </div>
    {% endfor %}
  </div>


</body>
</html>
{% endblock %}

Eshop/store/templates/login.html
{%load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
  <link href="{% static 'css/login.css' %}" rel="stylesheet">
</head>
<body>
  <div class="login-container">
    <h2>Login</h2>
    <form id="login-form" method="POST">
      {% csrf_token %}
     
      <input type="text" id="username" placeholder="Username" name="username">
      <input type="password" id="password" placeholder="Password" name="password">
      <button type="submit">Login</button>
    </form>
    <h4>New to this website ?<a href="{% url 'register'%}">Register</a></h4>
  </div>

  <script src="script.js"></script>
</body>
</html>

Eshop/store/templates/payment.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Payment</title>
    <link href="{% static 'css/payment.css' %}" rel="stylesheet">
</head>
<body>
    <h1 class="top">Make Payment</h1>
    <div class="product-details">
        <img src="{{ item.image.url }}" alt="{{ item.name }}">
        <h3>{{ item.name }}</h3>
        <span class="price">{{ item.price }}</span>
    </div>
    <form id="paymentForm" action="{% url 'payment_success' %}" method="post">
        {% csrf_token %}
        
        <input type="hidden" name="amount" value="{{ amount }}">
        <input type="hidden" name="order_id" value="{{ order_id }}">
        <script
            src="https://checkout.razorpay.com/v1/checkout.js"
            data-key=rzp_test_ecbAYxa2CJB8lo
            data-amount="{{ amount }}"
            data-currency="INR"
            data-order_id="{{ razorpay_order_id }}"
            data-buttontext="start Payment "
            data-name="Aunty Store"
            data-description="Payment for Order"
            data-image="{% static 'media\item_images\kurkure.jpeg' %}"
        ></script>
    </form>
</body>
</html>

Eshop/store/templates/payment_success.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
    <title>Payment Success</title>
    <link href="{% static 'css/payment_success.css' %}" rel="stylesheet">
</head>
<body>
    
    <h1 class='success'>Payment successful!</h1>
    <div>thank you for yourpurchase</div>
    <form action="{% url "home"%}">
        <button type="submit" class="button">Return to home</button>
     </form>
    
</body>
</html>

Eshop/store/templates/register.html
{%load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Registration</title>
  <link href="{% static 'css/register.css' %}" rel="stylesheet">
</head>
<body>
  <div class="registration-container">
    <h2>Registration</h2>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <form id="registration-form" method="POST" >
      {% csrf_token %}
      <input type="text" id="username" placeholder="name" name="uname">
      <input type="email" id="email" placeholder="Email" name="email">
      <input type="password" id="password" placeholder="Password" name="password">
      <input type="password" id="confirm-password" placeholder="Confirm Password" name="conpass">
      <button type="submit">Register</button>
      <h4>Already Have account?<a href="{% url 'login'%}">Login</a></h4>
    </form>
  </div>

  <script src="script.js"></script>
</body>
</html>